// This is a placeholder for Convex generated types
// In production, this file will be auto-generated by Convex

export const mutation = (config: any) => config;
export const query = (config: any) => config;
export const action = (config: any) => config;